### ISSUE TITLE
セッションハンドラのオプション化

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1719]
#1638

標準ではセッションハンドラはNativeFileSessionHandlerを利用している。
これを、設定によりmemcachedやredis等に切りかえられるように対応する。

custom-session-configurations
http://silex.sensiolabs.org/doc/providers/session.html#custom-session-configurations

デフォルトの挙動は、これまでどおり、NativeFileSessionHandlerを利用する
他のセッションハンドラに変更する場合は、save_handlerおよびsave_pathオプションで、使用するハンドラを設定する

設定例

```yml
session_handler:
    enabled: true
    save_handler: redis
    save_path: 127.0.0.1:6379
```

- enabled
    - 他のセッションハンドラを利用する場合, true
- save_handler: 
    - 使用するハンドラ
- save_path: 
    - ハンドラの設定

備考
- symfonyが提供しているセッションハンドラは、\SessionHandlerInterface(5.4～)の実装のため、現状では利用しない。
    - https://github.com/symfony/http-foundation/tree/2.7/Session/Storage/Handler
    - http://php.net/manual/ja/class.sessionhandlerinterface.php
