### ISSUE TITLE
http_cache.ymlで対象routeの設定が効かない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#1775]
- http_cache.yml.distを、app/config/eccube/http_cache.ymlに配置
- http_cache.ymlの設定を以下のように変更

```
http_cache:
    enabled: true
    age: 10
    # フロントでキャッシュを適用させる画面のrouteを設定
    route:
#        - homepage
#        - product_list
        - block_category
#        - block_news
#        - block_search_product
#        - help_about
#        - help_guide
#        - help_privacy
#        - help_tradelaw
#        - help_agreement
```

このとき、カテゴリブロックだけでなく、コメントアウトしたルーティングでもhttpキャッシュが有効になります。

array_replace_recursiveでは`route`自体を置き換えるわけではないようです。
http_cache.yml.distのrouteはコメントアウトしておいた方がよいかもしれません。
