### ISSUE TITLE
削除済みエンティティでもIDだけは取得する余地を残したい

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#2080]
Eccube.Entity.Order.dcm.yml
``` yaml
        # 前略
        customer_id:
            type: integer
            nullable: true
        # 後略
```

Order.php
``` php
    // 前略
    protected $customer_id;

    /**
     * Get customer_id
     *
     * @return integer
     */
    public function getCustomerId()
    {
        return $this->customer_id;
    }
    // 後略
```
