### ISSUE TITLE
HTTPキャッシュ利用時に本会員登録が完了しない

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#2635]
## 概要(Overview)

ブロック読み込み時に```TransactionListener::onKernelRequest()```が呼ばれる。

HTTPキャッシュが有効な際に、```GetResponseEvent::isMasterRequest()```がtrueとなり、```EntityMaster::beginTransaction()```が複数回呼ばれるもよう。

## 再現手順(Procedure)

0. 前提条件: index_dev.phpを利用しない。

1. HTTPキャッシュを[ドキュメント](http://doc.ec-cube.net/spec_config#http_cacheyml)に従って有効にする。

``` yaml
# /app/config/eccube/http_cache.yml
http_cache:
    enabled: true
    age: 10
    # フロントでキャッシュを適用させる画面のrouteを設定
    route:
        - homepage
        - product_list
        - block_category
        - block_news
        - block_search_product
        - help_about
        - help_guide
        - help_privacy
        - help_tradelaw
        - help_agreement
```

2. 仮会員機能を有効にする。

3. 任意の仮会員の本会員登録ページにアクセスし、以下を確認する。
  - 本登録が完了した旨が表示されている。
  - 画面上はマイページへのリンクが表示されている。
  - 本登録完了メールが送信されている。
  - 他の画面へ遷移するとマイページへのリンクの代わりに新規会員登録ページへのリンクが表示されている。
  - 管理画面やDBで仮会員のままになっている。

### 環境1

+ EC-CUBE: 3.0.11
+ PHP: 7.1.2
+ DB:
  - MySQL 5.5.45

### 環境2

+ EC-CUBE: 3.0.15
+ PHP: 7.1.2
+ DB:
  - PostgreSQL 9.2.20
