### ISSUE TITLE
4.0(旧3.n)ドキュメント化に向けた情報や実装の参考にしたい情報

### ISSUE THREAD

**Issue by t-nagahashi** [EC-CUBE/ec-cube#3380]
## 概要(Overview)
http://doc3n.ec-cube.net/ に追加していきたい内容や、
今後の実装の参考にしたいネタを書き留めておくためのIssue
随時、コメントなどで貯めていきます。好きにコメントいただいてもいいです。
見づらくなってきたりしたら、調整します。

## 関連情報 (Ref)
https://github.com/EC-CUBE/ec-cube/issues/1330

**Comment by ryo-endo** [comment]
利用者の方々により安心して使っていただけるプラグインを作っていただくために、3.nのプラグインとして推奨する実装方針や参考情報をまとめました。

※ご注意※  
まだ3.nが開発途中であることと、これからプラグイン開発者の皆様からのフィードバックを頂き改善を進めていくため、記載内容に変更が発生する可能性がございます。

---------------------------------------------------------------------------------------------------
## 命名規約について

プラグイン同士での名前の衝突(ルーティング名/テーブル名/定数名など)を避けるため、
命名規約への準拠をお願いします。

https://github.com/EC-CUBE/sample-payment-plugin/issues/6

---------------------------------------------------------------------------------------------------
## フロント/管理画面へのUI要素の追加について

デザインカスタマイズ時に表示がされなくなるなどのトラブルを避けるため、
以下の方法でのUI要素の追加を推奨します。

### TwigBlockを提供する方法 (フロント画面向け)
プラグインで独自のBlockを定義できます。
プラグイン利用者が、Twigファイル内にBlock表示用のコードを記述することでUI要素を追加できます。
    
詳細/サンプルコード
https://github.com/EC-CUBE/sample-payment-plugin#twig%E3%83%A6%E3%83%BC%E3%82%B6%E5%AE%9A%E7%BE%A9%E9%96%A2%E6%95%B0%E3%81%AE%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BF

### TemplateEventでUI要素を追加する方法 (フロント画面/管理画面向け)
TemplateEventを利用することで「`</body>`タグ直前」または「`<head></head>`内」に出力するコードを追加できます。
ここにJavaScriptのコードを出力することでUI要素を追加できます。
    
詳細/サンプルコード
https://github.com/EC-CUBE/sample-payment-plugin#%E7%94%BB%E9%9D%A2%E3%81%B8%E3%81%AE%E4%BB%8B%E5%85%A5%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
    
### 非推奨
3.0系プラグインで利用されていた「Twigファイルの内容を正規表現で置き換える」方法は、
デザインカスタマイズ時や複数プラグイン導入時に表示されなくなるなどのトラブルが起きやすいため、
3.n系では非推奨となります。
    
---------------------------------------------------------------------------------------------------
## 3.n系で追加された拡張機構について

3.n系ではプラグインからも利用できる拡張機構が追加になりました。

従来のフックポイントを使った拡張も可能ですが、
拡張機構を使うことで、3.0系よりも少ないコードで、他のプラグインとも共存しやすい実装が可能になります。

### カラムの追加
Entityの拡張機構を使うことで、
既存のテーブルに対してプラグイン独自のカラムを追加することが可能になりました。
http://doc3n.ec-cube.net/customize_entity

### ソート順や検索条件の変更
Repositoryの拡張機構を使うことで、
ソート順や検索条件のカスタマイズを行いやすくなりました。
http://doc3n.ec-cube.net/customize_repository

### 購入フローのカスタマイズ
Serviceの拡張機構を使うことで、
カートや購入処理のカスタマイズが可能になります。
http://doc3n.ec-cube.net/customize_service
    
---------------------------------------------------------------------------------------------------
## プラグインのサンプルについて

サンプルプラグインでは、以下のような拡張を行っています。

### 商品レビュープラグイン
https://github.com/EC-CUBE/ProductReview-plugin/tree/experimental/sf
- フロント画面/管理画面への新規ページの追加
- TwigBlockによるUI要素の追加
- TemplateEventによるUI要素の追加
- プラグイン用テーブルの追加
- 管理画面サイドメニューへの項目追加
- プラグイン有効時/削除時の処理
- CSVの出力
    
### メーカー管理プラグイン
https://github.com/EC-CUBE/maker-plugin/tree/experimental/sf
- フォーム(ProductType)への項目の追加
- プラグイン用テーブルの追加
- Product(dtb_product)へのカラムの追加
- TwigBlockによるUI要素の追加
- 管理画面サイドメニューへの項目追加
    
---------------------------------------------------------------------------------------------------
## その他参考となる情報

EC-CUBE 3.n 開発ドキュメント
http://doc3n.ec-cube.net/

決済プラグイン向けサンプルのREADME
https://github.com/EC-CUBE/sample-payment-plugin/

GitHubで"document"ラベルの付いたIssue/Pullrequest
https://github.com/EC-CUBE/ec-cube/issues?utf8=%E2%9C%93&q=label%3Adocument+milestone%3A3.n.0+

**Comment by t-nagahashi** [comment]
# プラグイン作成者向け

利用者の方々により安心して使っていただけるプラグインを作っていただくために、
3.nのプラグインとして推奨する実装方針や参考情報をまとめました。

※まだ3.nが開発途中であることと、
  これからプラグイン開発者の皆様からのフィードバックを頂き改善を進めていくため、
  記載内容に変更が発生する可能性がございます。

※今回、3.n向けに移植させていただいたサンプルプラグインでは、
  これらの推奨内容を完全に満たせておりませんことをあらかじめご了承ください。

# 詳細説明

## 命名規約について

プラグイン同士での名前の衝突(ルーティング名/テーブル名/定数名など)を避けるため、
命名規約への準拠をお願いします。

https://github.com/EC-CUBE/sample-payment-plugin/issues/6

## フロント/管理画面へのUI要素の追加について

デザインカスタマイズ時に表示がされなくなるなどのトラブルを避けるため、
以下の方法でのUI要素の追加を推奨します。

### TwigBlockを提供する方法 (フロント画面向け)
    プラグインで独自のBlockを定義できます。
    プラグイン利用者が、Twigファイル内にBlock表示用のコードを記述することでUI要素を追加できます。
    
    詳細/サンプルコード
    https://github.com/EC-CUBE/sample-payment-plugin#twig%E3%83%A6%E3%83%BC%E3%82%B6%E5%AE%9A%E7%BE%A9%E9%96%A2%E6%95%B0%E3%81%AE%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BF

### TemplateEventでUI要素を追加する方法 (フロント画面/管理画面向け)
    TemplateEventを利用することで「</body>タグ直前」または「<head></head>内」に出力するコードを追加できます。
    ここにJavaScriptのコードを出力することでUI要素を追加できます。
    
    詳細/サンプルコード
    https://github.com/EC-CUBE/sample-payment-plugin#%E7%94%BB%E9%9D%A2%E3%81%B8%E3%81%AE%E4%BB%8B%E5%85%A5%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
    
### 非推奨
    3.0系プラグインで利用されていた「Twigファイルの内容を正規表現で置き換える」方法は、
    デザインカスタマイズ時や複数プラグイン導入時に表示されなくなるなどのトラブルが起きやすいため、
    3.n系では非推奨となります。
    
## 3.n系で追加された拡張機構について

3.n系ではプラグインからも利用できる拡張機構が追加になりました。

従来のフックポイントを使った拡張も可能ですが、
拡張機構を使うことで、3.0系よりも少ないコードで、他のプラグインとも共存しやすい実装が可能になります。

### カラムの追加
    Entityの拡張機構を使うことで、
    既存のテーブルに対してプラグイン独自のカラムを追加することが可能になりました。
    http://doc3n.ec-cube.net/customize_entity

### ソート順や検索条件の変更
    Repositoryの拡張機構を使うことで、
    ソート順や検索条件のカスタマイズを行いやすくなりました。
    http://doc3n.ec-cube.net/customize_repository

### 購入フローのカスタマイズ
    Serviceの拡張機構を使うことで、
    カートや購入処理のカスタマイズが可能になります。
    http://doc3n.ec-cube.net/customize_service

## プラグインのサンプルについて

サンプルプラグインでは、以下のような拡張を行っています。

### 商品レビュープラグイン
    https://github.com/EC-CUBE/ProductReview-plugin/tree/experimental/sf
    - フロント画面/管理画面への新規ページの追加
    - TwigBlockによるUI要素の追加
    - TemplateEventによるUI要素の追加
    - プラグイン用テーブルの追加
    - 管理画面サイドメニューへの項目追加
    - プラグイン有効時/削除時の処理
    - CSVの出力
    
### メーカー管理プラグイン
    https://github.com/EC-CUBE/maker-plugin/tree/experimental/sf
    - フォーム(ProductType)への項目の追加
    - プラグイン用テーブルの追加
    - Product(dtb_product)へのカラムの追加
    - TwigBlockによるUI要素の追加
    - 管理画面サイドメニューへの項目追加
    
### その他参考となる情報

EC-CUBE 3.n 開発ドキュメント
http://doc3n.ec-cube.net/

決済プラグイン向けサンプルのREADME
https://github.com/EC-CUBE/sample-payment-plugin/

GitHubで"document"ラベルの付いたIssue/Pullrequest
https://github.com/EC-CUBE/ec-cube/issues?utf8=%E2%9C%93&q=label%3Adocument+milestone%3A3.n.0+

**Comment by t-nagahashi** [comment]
# EC-CUBE 3.n インストール方法
https://github.com/EC-CUBE/sample-payment-plugin#ec-cube%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E6%89%8B%E9%A0%86

**Comment by Yangsin** [comment]
# ログ出力方法

ログ出力のグローバル関数が用意されているのでどこからでも呼び出せる。

```php
log_info('ログメッセージ');
```

ログレベル別に関数がわかれているので適切な関数を利用すること。

```php
log_emergency()
log_alert()
log_critical()
log_error()
log_warning()
log_notice()
log_info()
log_debug()
```

関数の定義は以下

`/src/Eccube/Resource/functions/log.php`

# ログの出力先

`/var/log/` 配下に出力される。

環境に合わせてさらにディレクトリが別れる。
環境の設定は `.env` ファイルの `APP_ENV` で指定可能。

例えば

- 本番環境( `APP_ENV=prod` )のときは `/var/log/prod` 配下にログ出力される。
- 開発環境( `APP_ENV=dev` )のときは `/var/log/dev` 配下にログ出力される。

# ログの設定変更

環境ごとの設定ファイルを修正してログの設定変更が可能。

例えば

- 本番環境( `APP_ENV=prod` )の設定は `/app/config/eccube/packages/prod/monolog.yml` に記載されている。
- 開発環境( `APP_ENV=dev` )の設定は `/app/config/eccube/packages/dev/monolog.yml` に記載されている。

# 参考

- https://github.com/EC-CUBE/ec-cube/pull/2761
- https://github.com/EC-CUBE/ec-cube/pull/2766
- https://github.com/EC-CUBE/ec-cube/pull/2716


`log_info('ログメッセージ');` でログメッセージを出力可能です。特別な設定は不要ですが、 `.env` ファイルの `APP_ENV` の値で設定が若干変わります。詳細は添付のマークダウンをご確認ください。

**Comment by ryo-endo** [comment]
## プラグインで管理画面のメニューを追加する方法

ルート階層に追加できないなどの課題があったため #3450 で修正を行いました。
これに伴い、EccubeNavインターフェイスのgetNav関数の仕様が変更となります。

新しい実装例
```php
<?php

namespace Customize;

use Eccube\Common\EccubeNav;

class CustomizeNav implements EccubeNav
{
    /**
     * @return array
     */
    public static function getNav()
    {
        return [
            // 商品管理に子メニューを追加する場合のサンプル
            'product' => [
                'children' => [
                    'sampleplugin_my_product_menu_item' => [
                        'name' => '商品管理の子（追加）',
                        'url' => 'admin_homepage',
                    ],
                ],
            ],
            // 第一階層からオリジナルのメニューを追加する場合のサンプル
            'sampleplugin_my_root_menu' => [
                'name' => '1階層メニュー（追加）',
                'icon' => 'fa-cube',
                'children' => [
                    'sampleplugin_my_menu_item' => [
                        'name' => '2階層メニュー（子なし）',
                        'url' => 'admin_homepage',
                    ],
                    'sampleplugin_my_menu' => [
                        'name' => '2階層メニュー（子あり）',
                        'children' => [
                            'sampleplugin_my_menu_item1' => [
                                'name' => '3階層メニュー1',
                                'url' => 'admin_homepage',
                            ],
                            'sampleplugin_my_menu_item2' => [
                                'name' => '3階層メニュー2',
                                'url' => 'admin_homepage',
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
}
```

**Comment by ryo-endo** [comment]
## コントローラの無いtwigの拡張方法

EC-CUBE 3.n alpha-5 までは拡張できませんでしたが、#3441 の修正で「コントローラのあるtwig」 と同じ実装方法で拡張できるようになりました。

実装例： https://github.com/EC-CUBE/ProductReview-plugin/blob/038b915c815f786c5ff5c22c1a3c94ae15f0dc54/ProductReviewEvent.php#L60

**Comment by ryo-endo** [comment]
フロント画面の拡張についてですが、「includeを利用する方法」が推奨となりました。
(「TwigBlockを提供する方法」はincludeで代替ができます)

記載UPdateしております。
https://github.com/EC-CUBE/ec-cube/issues/3380#issuecomment-406917903

**Comment by ryo-endo** [comment]
## 受注のステートマシン
4.0-beta 以降の受注は以下のステートマシンに則って実装してあります。
https://github.com/EC-CUBE/ec-cube/pull/3325

**Comment by ryo-endo** [comment]
## コントローラのRoute/Methodアノテーションの記載方法について

### 背景
Sensio\Bundle\FrameworkExtraBundle\Configuration\Route
Sensio\Bundle\FrameworkExtraBundle\Configuration\Method
がdeprecatedのため、以下の新しい記載方法を推奨します。

### Routeアノテーションの変更

ルーティング定義に
`use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;`
を利用していたのを
`use Symfony\Component\Routing\Annotation\Route;`
に変更。

※アノテーションの記述方法は今までと同じ

### Methodアノテーションの変更

廃止：
`use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;`
を利用して
`@Method('DELETE')`
等のようにHTTPメソッドを宣言していたのを廃止。

新：
Routeアノテーション定義の中にあるmethodsパラメータに対して設定
`@Route("/products/add_cart/{id}", name="product_add_cart", methods={"POST"}, requirements={"id" = "\d+"})`

※宣言が必要なければmethodsは省略可能

**Comment by okazy** [comment]
## プラグインから独自にログファイルを出力する方法

### 対応したPR

https://github.com/EC-CUBE/ec-cube/pull/3530

### プラグインでの利用方法

1. `[プラグインディレクトリ]/Resource/config/services.yaml` というファイルを作成する。
2. 作成したservices.yamlに対して以下の内容を記述する。  
```yml
monolog:
    channels: ['プラグインコード名']
    handlers:
        プラグインコード名:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: プラグインコード名_rotating_file
            channels: ['プラグインコード名']
            channels: ['!event', '!doctrine']
        プラグインコード名_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/出力したファイル名.log'
            formatter: eccube.log.formatter.line
            level: debug
```
3. プラグインからは以下のように呼び出す
```
logs('プラグインコード名')->info('ああああああ');
```
4. ログの内容が出力されているかどうか確認
```
[EC-CUBEのディレクトリ]/var/log/[prodまたはdev等]/出力したファイル名-YYYY-MM-DD.log
```
5. ログフォーマッットの記述を変更したい時は以下を設定する。
```yml
services:
    プラグインコード名.log.formatter.line:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%level_name%% [%%extra.session_id%%] %%message%% [%%extra.ip%%, %%extra.referrer%%, %%extra.user_agent%%]\n"

monolog:
    channels: ['プラグインコード名']
    handlers:
        プラグインコード名:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: プラグインコード名_rotating_file
            channels: ['プラグインコード名']
            channels: ['!event', '!doctrine']
        プラグインコード名_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/出力したファイル名.log'
            formatter: プラグインコード名.log.formatter.line
            level: debug
```
上記のargumentsにある設定で出力する内容が変更可能。
```
logs('プラグインコード名')->info('ああああああ');
```
と出力した場合、`%%message%% ` に `ああああああ` が出力される。
