### ISSUE TITLE
4.0.0のapache bench結果

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube#3913]
4.0.0の性能検証の結果です。

## 計測環境

さくらのクラウド

- サーバプラン : 1 GB / 1 仮想コア
- HDD : 20 GB SSDプラン
- ディスクイメージ : CentOS7.5 64bit
- PostgreSQL 9.2
- Apache 2.4.6
- PHP 7.1.21
    - apcu, opcache有効

デフォルトインストールされた状態で、トップページ/商品一覧ページをApache Bench(v2.3)で計測
Apache Benchの実行は別サーバから行う

`ab -n 100 -c 10 http://xxx.xxx.xxx/`

### トップページ

| -                      | 初期状態 | 商品規格数：9万点 |
|------------------------|----------|-------------------|
| 4.0.0                  | 29.306   | 23.016            |
| 3.0.16(デフォルト)     | 13.828   | 12.874            |
| 3.0.16(キャッシュ設定) | 31.388   | 27.608            |

### 商品一覧ページ

| -                      | 初期状態 | 商品規格数：9万点 |
|------------------------|----------|-------------------|
| 4.0.0                  | 18.234   | 6.032             |
| 3.0.16(デフォルト)     | 8.974    | 2.996           |
| 3.0.16(キャッシュ設定) | 15.716   | 3.172             |

※結果はRequest Per Secondの値(5回計測した際の平均値)を記載

## 前提条件

各バージョンの条件

- 4.0.0：APP_ENV=prod、APP_DEBUG=0
- 3.0.16(デフォルト)：キャッシュ設定なしのデフォルト状態
- 3.0.16(キャッシュ設定)：doctrine_cache設定, config_cache_php設定を有効

データの条件

- 初期状態 -> EC-CUBEをインストール直後の状態
- 商品規格数：9万点 -> 商品数：1万 / 商品規格：3x3 / カテゴリ数：30件

**Comment by okihika** [comment]
質問・要望があります。

計測環境について
PostgreSQLはApacheが動作してるサーバー上で動いていますか？それとも別ホストで可動していますか?
計測結果の傾向に影響があるかは不明ですが、気になりました。

設定について
doctrine_cacheのドライバは何(filesystem/apcなど)を指定していますか?
可能であれば、doctrine_cache.ymlの設定値を公開してほしいです。

計測対象について
商品詳細ページ(/products/detail/)も計測していたら結果を知りたいです。

**Comment by chihiro-adachi** [comment]
@okihika 

> PostgreSQLはApacheが動作してるサーバー上で動いていますか？それとも別ホストで可動していますか?

ApacheとPostgreSQLは同一サーバ上で稼働しています

> doctrine_cacheのドライバは何(filesystem/apcなど)を指定していますか?
> 可能であれば、doctrine_cache.ymlの設定値を公開してほしいです。

4.0については、filesystemを使用。doctrineの設定に変更はありません。
3.0については、filesystemを使用。doctrine_cache.yamlは以下です。
```
doctrine_cache:
  metadata_cache:
    driver: filesystem
    path: /path/to/cache/meta
    host:
    port:
    password:
  query_cache:
    driver: filesystem
    path: /path/to/cache/query
    host:
    port:
    password:
  result_cache:
    driver: filesystem
    path: /path/to/cache/result
    host:
    port:
    password:
    lifetime: 3600
    clear_cache: true
  hydration_cache:
    driver: array
    path:
    host:
    port:
    password:
```

> 商品詳細ページ(/products/detail/)も計測していたら結果を知りたいです。

すみません、こちらは計測できていないです。
