### ISSUE TITLE
docker-composeにおける.envのファイル名重複

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube#3927]
## 概要(Overview)

下記のようにdocker-compose関連ファイルを含めたいケースで.envファイルが重複してしまう。

(docker-compose側では.env以外のファイルを読めない。関連情報を参照。)

``` yml
# docker-compose.yml
version: "3"
services:
  php:
    build: "php:7.1-apache"
    ports:
      - "${HTTP_PORT}:80"
```

``` env
# .default.env
HTTP_PORT=8080
```

``` sh
$ cp .default.env .env
$ docker-compose up -d --build
```

## 要望 (Requirement)

対応例

- .envをappディレクトリ以下に移動する
- .envの設置場所を変更可能とする
- .env.eccubeのような名前とする

### 環境 (environment)

+ EC-CUBE: 4.0

## 関連情報 (Ref)

https://qiita.com/friedaji/items/c1894821a2c49395cfd7

**Comment by nanasess** [comment]
.env ファイルを使わずに、 docker-compose から環境変数を設定することで対応できませんでしょうか?

**Comment by izayoi256** [comment]
環境変数の数が多いケースで大変かと思いまして。不便を我慢すれば大丈夫な程度の問題ではあるのですが…。

**Comment by izayoi256** [comment]
こういうことですよね？

``` sh
$ HTTP_PORT=8080 docker-compose up -d --build
```

**Comment by nanasess** [comment]
いえ、 EC-CUBE で使用する環境変数を docker-compose で渡せると思います。
環境変数 `APP_ENV` がサーバー側で設定されていると .env は参照しないので、docker-compose にこんな感じで書いておけば大丈夫かと

```yaml
  php:
    build: "php:7.1-apache"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=pgsql://postgres:password@127.0.0.1/cube4_dev
      - ECCUBE_AUTH_MAGIC=8PPlCHZVdH5vbMkIUKeuTeDHycQQMuaB
      - DATABASE_SERVER_VERSION=10.2
      - MAILER_URL=smtp://localhost:1025
      - ECCUBE_ADMIN_ALLOW_HOSTS=[]
      - ECCUBE_FORCE_SSL=false
      - ECCUBE_ADMIN_ROUTE=admin
      - ECCUBE_COOKIE_PATH=/
```

**Comment by izayoi256** [comment]
> 環境変数 APP_ENV がサーバー側で設定されていると .env は参照しないので

こちらを参考に、下記のような方法で対応ができました。ありがとうございます。

``` yml
# docker-compose.yml
    environment:
      - APP_ENV=${ECCUBE_APP_ENV}
      - APP_DEBUG=${ECCUBE_APP_DEBUG}
      - DATABASE_URL=${ECCUBE_DATABASE_URL}
      - DATABASE_SERVER_VERSION=${ECCUBE_DATABASE_SERVER_VERSION}
      - MAILER_URL=${ECCUBE_MAILER_URL}
      - ECCUBE_AUTH_MAGIC=${ECCUBE_AUTH_MAGIC}
      - TRUSTED_PROXIES=${ECCUBE_TRUSTED_PROXIES}
      - TRUSTED_HOSTS=${ECCUBE_TRUSTED_HOSTS}
      - ECCUBE_LOCALE=${ECCUBE_LOCALE}
      - ECCUBE_TIMEZONE=${ECCUBE_TIMEZONE}
      - ECCUBE_CURRENCY=${ECCUBE_CURRENCY}
      - ECCUBE_ADMIN_ROUTE=${ECCUBE_ADMIN_ROUTE}
      - ECCUBE_USER_DATA_ROUTE=${ECCUBE_USER_DATA_ROUTE}
      - ECCUBE_ADMIN_ALLOW_HOSTS=${ECCUBE_ADMIN_ALLOW_HOSTS}
      - ECCUBE_FORCE_SSL=${ECCUBE_FORCE_SSL}
      - ECCUBE_TEMPLATE_CODE=${ECCUBE_TEMPLATE_CODE}
      - ECCUBE_COOKIE_NAME=${ECCUBE_COOKIE_NAME}
      - ECCUBE_COOKIE_PATH=${ECCUBE_COOKIE_PATH}
      - ECCUBE_COOKIE_LIFETIME=${ECCUBE_COOKIE_LIFETIME}
      - ECCUBE_GC_MAXLIFETIME=${ECCUBE_GC_MAXLIFETIME}
    ports:
      - "${HTTP_PORT}:80"
```

``` env
# .default.env
HTTP_PORT=8080

ECCUBE_APP_ENV=dev
ECCUBE_APP_DEBUG=1
ECCUBE_DATABASE_URL=sqlite:///%kernel.project_dir%/var/eccube.db
ECCUBE_DATABASE_SERVER_VERSION=3
ECCUBE_MAILER_URL=null://localhost
ECCUBE_AUTH_MAGIC=supersecureauthmagic
ECCUBE_LOCALE=ja
ECCUBE_TIMEZONE=Asia/Tokyo
ECCUBE_CURRENCY=JPY
ECCUBE_ADMIN_ROUTE=admin
ECCUBE_USER_DATA_ROUTE=user_data
ECCUBE_ADMIN_ALLOW_HOSTS=[]
ECCUBE_FORCE_SSL=false
ECCUBE_TEMPLATE_CODE=default
ECCUBE_COOKIE_NAME=eccube
ECCUBE_COOKIE_PATH=/
ECCUBE_COOKIE_LIFETIME=0
ECCUBE_GC_MAXLIFETIME=1440
```

``` sh
$ cp .default.env .env
$ docker-compose up -d --build
$ docker exec -u www-data ec-cube_php_1 php bin/console eccube:install -n
$ curl -D - -s -o /dev/null http://localhost:8080/
HTTP/1.1 200 OK
Date: Wed, 17 Oct 2018 04:34:21 GMT
Server: Apache/2.4.25 (Debian)
X-Powered-By: PHP/7.1.23
Set-Cookie: eccube=d56bd29eb5844b8664552d2dd027eb04; path=/; HttpOnly
Cache-Control: max-age=0, must-revalidate, private
X-Debug-Token: 5689d1
X-Debug-Token-Link: http://localhost:8080/_profiler/5689d1
Set-Cookie: device_view=full; expires=Sat, 17-Nov-2018 04:34:21 GMT; Max-Age=2678400; path=/; httponly
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
```
