### ISSUE TITLE
app/Resources/config/resources.yaml に設定を追加しても期待した動作をしない

### ISSUE THREAD

**Issue by fni-pj** [EC-CUBE/ec-cube#4620]
## 概要(Overview)

```yaml
services:
  # 既存の ProductRepository を拡張
  Customize\Repository\ProductRepository:
    decorates: Eccube\Repository\ProductRepository
```

app/Customize/config/resources.yaml に、上記設定を追加して動かすと、
`Type error: Too few arguments to function Customize\Repository\ProductRepository::__construct(), 0 passed`
というエラーが発生する。

`app/config/eccube/services.yaml` の末尾に追記するとエラーが発生せず期待通りの動作をする。

`Customize\Repository\ProductRepository` は `Eccube\Repository\ProductRepository` を継承。

## 期待する内容(Expect)  or 要望 (Requirement)

`app/config/eccube/services.yaml` の末尾に追記したときと同じ動作をしてほしい。

## 再現手順(Procedure)

`Eccube\Repository\ProductRepository` を継承した Repository を作成し、`app/config/eccube/services.yaml` に設定を追加。

### 環境 (environment)

+ Docker: php:7.3-apache-buster
+ EC-CUBE: 4.0.4
+ PHP: 7.3.18
+ DB:
  - MySQL 5.7.30

**Comment by chihiro-adachi** [comment]
@fni-pj 
app/Resources/config/resources.yamlは読みに行かないので、
app/Customize/Resource/config/services.yamlに置くとどうでしょうか。

**Comment by fni-pj** [comment]
すみません、app/Resources/config/resources.yaml はtypoです
実際にはapp/Customize/Resource/config/services.yaml
にファイルを置いています。

**Comment by kiy0taka** [comment]
デコレーターパターンを利用する場合は、デコレーターのコンストラクタに元のインスタンスを渡す必要があるかと思います。
https://symfony.com/doc/3.4/service_container/service_decoration.html

```
services:
  # 既存の ProductRepository を拡張
  Customize\Repository\ProductRepository:
    decorates: Eccube\Repository\ProductRepository
    arguments: ['@Customize\Repository\ProductRepository.inner']
```
