### ISSUE TITLE
HTMLPurifierBundleで作成されるキャッシュファイルを削除したい

### ISSUE THREAD

**Issue by k-yamamura** [EC-CUBE/ec-cube#6087]
### 概要(Overview)

特定のサーバ環境にてキャッシュを削除する際に、
`rm -rf var/cache` を実行すると、
```
rm -rf var/cache/
rm: 'var/cache/prod/htmlpurifier/CSS/4.15.0,4114918a13a428a8482a8a449792a5a8747582b5,1.ser' を削除できません: 許可がありません
rm: 'var/cache/prod/htmlpurifier/HTML/4.15.0,b07be21d7969cbd4a9416a819ac8ad9943060d47,1.ser' を削除できません: 許可がありません
rm: 'var/cache/prod/htmlpurifier/URI/4.15.0,3478238e680361cd87bf880f5b3cc50a1e7abc6c,1.ser' を削除できません: 許可がありません
```

と表示されてhtmlpurifierで作成されたキャッシュファイルがパーミッションの関係で削除されない。
rootユーザで実行すると当然削除されるが、ユーザ関係なく削除できるようにしたい。

EC-CUBE:4.1.x、4.2.x

参考url : https://github.com/Exercise/HTMLPurifierBundle/issues/22

### 期待する内容(Expect) or 要望(Requirement)

`app/config/eccube/packages`配下に、

- exercise_html_purifier.yaml
```yaml
exercise_html_purifier:
    html_profiles:
        default:
            config:
                Cache.SerializerPermissions: 0777
```

設定ファイルを作成すると削除されるようになるため、この設定ファイルの導入可否を検討してください。

参考url : https://github.com/Exercise/HTMLPurifierBundle#configuration
