### ISSUE TITLE
インストール時に、SMTPユーザー/パスワードを指定しても、 SMTP認証が有効にならない場合がある

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube#704]
インストール時に、 SMTPユーザー/パスワードを指定した場合、以下のような設定ファイルが生成される

```yaml
mail:
    transport: smtp
    host: <SMTP Host>
    port: <SMTP Port>
    username: <SMTP User>
    password: <SMTP Password>
    encryption: null
    auth_mode: null
```

環境依存の可能性もあるが、 `auth_mode: Plain` を指定する必要がある？

```yaml
mail:
    transport: smtp
    host: <SMTP Host>
    port: <SMTP Port>
    username: <SMTP User>
    password: <SMTP Password>
    encryption: null
    auth_mode: Plain
```

### 環境
- Windows7
- PHP5.5.11
- IIS8.0-Express

**Comment by k-yamamura** [comment]
インストール画面でメールサーバ設定を行うと、
app/config/eccube/mail.yml
に以下の内容が作成されますがauth_modeがnullでも問題なく送信できました。
portはOP25B対策しています。
'''
mail:
    transport: smtp
    host: ドメイン名
    port: 587
    username: ユーザー名
    password: パスワード
    encryption: null
    auth_mode: null
'''
おそらく環境か設定の問題かと思われます。

**Comment by k-yamamura** [comment]
Gmailの場合、
```
mail:
    transport: smtp
    host: smtp.gmail.com
    port: 465
    username: GMAILのユーザー名
    password: GMAILのパスワード
    encryption: ssl
    auth_mode: login
```
という設定で送信可能ですが、
Gmail側で安全性の低いアプリへのアクセスを有効にする必要がありました。
